apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    knative.dev/crd-install: "true"
    duck.knative.dev/addressable: "true"
    app.kubernetes.io/version: 1.19.4
    app.kubernetes.io/name: knative-eventing
  name: integrationsinks.sinks.knative.dev
spec:
  group: sinks.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sink
    kind: IntegrationSink
    plural: integrationsinks
    singular: integrationsink
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.address.url
      name: URL
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].reason
      name: Reason
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: IntegrationSink sends events to generic event sink
        properties:
          spec:
            description: Spec defines the desired state of the IntegrationSink.
            properties:
              log:
                properties:
                  loggerName:
                    default: log-sink
                    description: Name of the logging category to use
                    title: Logger Name
                    type: string
                  level:
                    default: INFO
                    description: Logging level to use
                    title: Log Level
                    type: string
                  logMask:
                    default: false
                    description: Mask sensitive information like password or passphrase in the log
                    title: Log Mask
                    type: boolean
                  marker:
                    description: An optional Marker name to use
                    title: Marker
                    type: string
                  multiline:
                    default: false
                    description: If enabled then each information is outputted on a newline
                    title: Multiline
                    type: boolean
                  showAllProperties:
                    default: false
                    description: Show all of the exchange properties (both internal and custom)
                    title: Show All Properties
                    type: boolean
                  showBody:
                    default: true
                    description: Show the message body
                    title: Show Body
                    type: boolean
                  showBodyType:
                    default: true
                    description: Show the body Java type
                    title: Show Body Type
                    type: boolean
                  showExchangePattern:
                    default: true
                    description: Shows the Message Exchange Pattern (or MEP for short)
                    title: Show Exchange Pattern
                    type: boolean
                  showHeaders:
                    default: false
                    description: Show the headers received
                    title: Show Headers
                    type: boolean
                  showProperties:
                    default: false
                    description: Show the exchange properties (only custom). Use showAllProperties to show both internal and custom properties.
                    title: Show Properties
                    type: boolean
                  showStreams:
                    default: false
                    description: Show the stream bodies (they may not be available in following steps)
                    title: Show Streams
                    type: boolean
                  showCachedStreams:
                    default: true
                    description: Whether Camel should show cached stream bodies or not.
                    title: Show Cached Streams
                    type: boolean
                type: object
              aws:
                properties:
                  s3:
                    properties:
                      arn:
                        description: The S3 Bucket name or Amazon Resource Name (ARN).
                        title: Bucket Name
                        type: string
                      deleteAfterRead:
                        default: true
                        description: Specifies to delete objects after consuming them.
                        title: Auto-delete Objects
                        type: boolean
                      moveAfterRead:
                        default: false
                        description: Move objects from S3 bucket to a different bucket after they have been retrieved.
                        title: Move Objects After Delete
                        type: boolean
                      destinationBucket:
                        description: Define the destination bucket where an object must be moved when moveAfterRead is set to true.
                        title: Destination Bucket
                        type: string
                      destinationBucketPrefix:
                        description: Define the destination bucket prefix to use when an object must be moved, and moveAfterRead is set to true.
                        title: Destination Bucket Prefix
                        type: string
                      destinationBucketSuffix:
                        description: Define the destination bucket suffix to use when an object must be moved, and moveAfterRead is set to true.
                        title: Destination Bucket Suffix
                        type: string
                      region:
                        description: The AWS region to access.
                        title: AWS Region
                        type: string
                      autoCreateBucket:
                        default: false
                        description: Specifies to automatically create the S3 bucket.
                        title: Autocreate Bucket
                        type: boolean
                      prefix:
                        description: The AWS S3 bucket prefix to consider while searching.
                        example: folder/
                        title: Prefix
                        type: string
                      ignoreBody:
                        default: false
                        description: If true, the S3 Object body is ignored. Setting this to true overrides any behavior defined by the `includeBody` option. If false, the S3 object is put in the body.
                        title: Ignore Body
                        type: boolean
                      uriEndpointOverride:
                        description: The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option.
                        title: Overwrite Endpoint URI
                        type: string
                      overrideEndpoint:
                        default: false
                        description: Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option.
                        title: Endpoint Overwrite
                        type: boolean
                      forcePathStyle:
                        default: false
                        description: Forces path style when accessing AWS S3 buckets.
                        title: Force Path Style
                        type: boolean
                      delay:
                        default: 500
                        description: The number of milliseconds before the next poll of the selected bucket.
                        title: Delay
                        type: integer
                      maxMessagesPerPoll:
                        default: 10
                        description: Gets the maximum number of messages as a limit to poll at each polling. Gets the maximum number of messages as a limit to poll at each polling. The default value is 10. Use 0 or a negative number to set it as unlimited.
                        title: Max Messages Per Poll
                        type: integer
                    type: object
                  sqs:
                    properties:
                      arn:
                        description: The SQS Queue Name or ARN
                        title: Queue Name
                        type: string
                      deleteAfterRead:
                        default: true
                        description: Delete messages after consuming them
                        title: Auto-delete Messages
                        type: boolean
                      region:
                        description: The AWS region to access.
                        title: AWS Region
                        type: string
                      autoCreateQueue:
                        default: false
                        description: Setting the autocreation of the SQS queue.
                        title: Autocreate Queue
                        type: boolean
                      host:
                        default: amazonaws.com
                        description: The hostname of the Amazon AWS cloud.
                        title: AWS Host
                        type: string
                      protocol:
                        default: https
                        description: The underlying protocol used to communicate with SQS
                        example: http or https
                        title: Protocol
                        type: string
                      queueURL:
                        description: The full SQS Queue URL (required if using KEDA)
                        title: Queue URL
                        type: string
                      uriEndpointOverride:
                        description: The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option.
                        title: Overwrite Endpoint URI
                        type: string
                      overrideEndpoint:
                        default: false
                        description: Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option.
                        title: Endpoint Overwrite
                        type: boolean
                      delay:
                        default: 500
                        description: The number of milliseconds before the next poll of the selected stream
                        title: Delay
                        type: integer
                      greedy:
                        default: false
                        description: If greedy is enabled, then the polling will happen immediately again, if the previous run polled 1 or more messages.
                        title: Greedy Scheduler
                        type: boolean
                      maxMessagesPerPoll:
                        default: 1
                        description: The maximum number of messages to return. Amazon SQS never returns more messages than this value (however, fewer messages might be returned). Valid values 1 to 10. Default 1.
                        title: Max Messages Per Poll
                        type: integer
                      waitTimeSeconds:
                        description: The duration (in seconds) for which the call waits for a message to arrive in the queue before returning. If a message is available, the call returns sooner than WaitTimeSeconds. If no messages are available and the wait time expires, the call does not return a message list.
                        title: Wait Time Seconds
                        type: integer
                      visibilityTimeout:
                        description: The duration (in seconds) that the received messages are hidden from subsequent retrieve requests after being retrieved by a ReceiveMessage request.
                        title: Visibility Timeout
                        type: integer
                    type: object
                  sns:
                    properties:
                      arn:
                        description: The SNS topic name name or Amazon Resource Name (ARN).
                        title: Topic Name
                        type: string
                      region:
                        description: The AWS region to access.
                        title: AWS Region
                        type: string
                      autoCreateTopic:
                        default: false
                        description: Setting the autocreation of the SNS topic.
                        title: Autocreate Topic
                        type: boolean
                      uriEndpointOverride:
                        description: The overriding endpoint URI. To use this option, you must also select the `overrideEndpoint` option.
                        title: Overwrite Endpoint URI
                        type: string
                      overrideEndpoint:
                        default: false
                        description: Select this option to override the endpoint URI. To use this option, you must also provide a URI for the `uriEndpointOverride` option.
                        title: Endpoint Overwrite
                        type: boolean
                    type: object
                  auth:
                    description: Auth configurations
                    properties:
                      secret:
                        description: Auth secret
                        properties:
                          ref:
                            description: |
                              Secret reference.
                            properties:
                              name:
                                description: Secret name
                                type: string
                            required:
                            - name
                            type: object
                        type: object
                    type: object
                type: object
            type: object
          status:
            description: Status represents the current state of the IntegrationSink. This data may be out of date.
            properties:
              address:
                description: IntegrationSink is Addressable. It exposes the endpoints as URIs to get events delivered into the used Kamelet.
                properties:
                  name:
                    type: string
                  url:
                    type: string
                  CACerts:
                    type: string
                  audience:
                    type: string
                type: object
              addresses:
                description: IntegrationSink is Addressable. It exposes the endpoints as URIs to get events delivered into the used Kamelet.
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    url:
                      type: string
                    CACerts:
                      type: string
                    audience:
                      type: string
                type: array
              annotations:
                description: Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              policies:
                description: List of applied EventPolicies
                items:
                  type: object
                  properties:
                    apiVersion:
                      description: The API version of the applied EventPolicy. This indicates, which version of EventPolicy is supported by the resource.
                      type: string
                    name:
                      description: The name of the applied EventPolicy
                      type: string
                type: array
              conditions:
                description: Conditions the latest available observations of a resource's current state.
                items:
                  type: object
                  required:
                  - type
                  - status
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time the condition transitioned from one status to another. We use VolatileTime in place of metav1.Time to exclude this from creating equality.Semantic differences (all other things held constant).
                      type: string
                    message:
                      description: A human readable message indicating details about the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    severity:
                      description: Severity with which to treat failures of this type of condition. When this is not specified, it defaults to Error.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition.
                      type: string
                type: array
              observedGeneration:
                description: ObservedGeneration is the 'Generation' of the Service that was last processed by the controller.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}