using k8s;
using k8s.Models;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

namespace KubernetesCRDModelGen.Models.apigateway.cnrm.cloud.google.com;
/// <summary></summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigMetadata
{
}

/// <summary>Backend settings that are applied to all backends of the Gateway.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigSpecGatewayConfigBackendConfig
{
    /// <summary>Immutable. Google Cloud IAM service account used to sign OIDC tokens for backends that have authentication configured (https://cloud.google.com/service-infrastructure/docs/service-management/reference/rest/v1/services.configs#backend).</summary>
    [JsonPropertyName("googleServiceAccount")]
    public string GoogleServiceAccount { get; set; }
}

/// <summary>Immutable. Immutable. Gateway specific configuration. If not specified, backend authentication will be set to use OIDC authentication using the default compute service account.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigSpecGatewayConfig
{
    /// <summary>Backend settings that are applied to all backends of the Gateway.</summary>
    [JsonPropertyName("backendConfig")]
    public APIGatewayAPIConfigSpecGatewayConfigBackendConfig BackendConfig { get; set; }
}

/// <summary>Immutable. Input only. File descriptor set, generated by protoc. To generate, use protoc with imports and source info included. For an example test.proto file, the following command would put the value in a new file named out.pb.  $ protoc --include_imports --include_source_info test.proto -o out.pb.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigSpecGrpcServicesFileDescriptorSet
{
    /// <summary>Immutable. Base64 encoded content of the file.</summary>
    [JsonPropertyName("contents")]
    public string Contents { get; set; }

    /// <summary>Immutable. The file path (full or relative path). This is typically the path of the file when it is uploaded.</summary>
    [JsonPropertyName("path")]
    public string Path { get; set; }
}

/// <summary></summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigSpecGrpcServicesSource
{
    /// <summary>Immutable. Base64 encoded content of the file.</summary>
    [JsonPropertyName("contents")]
    public string Contents { get; set; }

    /// <summary>Immutable. The file path (full or relative path). This is typically the path of the file when it is uploaded.</summary>
    [JsonPropertyName("path")]
    public string Path { get; set; }
}

/// <summary></summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigSpecGrpcServices
{
    /// <summary>Immutable. Input only. File descriptor set, generated by protoc. To generate, use protoc with imports and source info included. For an example test.proto file, the following command would put the value in a new file named out.pb.  $ protoc --include_imports --include_source_info test.proto -o out.pb.</summary>
    [JsonPropertyName("fileDescriptorSet")]
    public APIGatewayAPIConfigSpecGrpcServicesFileDescriptorSet FileDescriptorSet { get; set; }

    /// <summary>Uncompiled proto files associated with the descriptor set, used for display purposes (server-side compilation is not supported). These should match the inputs to 'protoc' command used to generate fileDescriptorSet.</summary>
    [JsonPropertyName("source")]
    public IList<APIGatewayAPIConfigSpecGrpcServicesSource>? Source { get; set; }
}

/// <summary></summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigSpecManagedServiceConfigs
{
    /// <summary>Immutable. Base64 encoded content of the file.</summary>
    [JsonPropertyName("contents")]
    public string Contents { get; set; }

    /// <summary>Immutable. The file path (full or relative path). This is typically the path of the file when it is uploaded.</summary>
    [JsonPropertyName("path")]
    public string Path { get; set; }
}

/// <summary>The OpenAPI Specification document file.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigSpecOpenapiDocumentsDocument
{
    /// <summary>Immutable. Base64 encoded content of the file.</summary>
    [JsonPropertyName("contents")]
    public string Contents { get; set; }

    /// <summary>Immutable. The file path (full or relative path). This is typically the path of the file when it is uploaded.</summary>
    [JsonPropertyName("path")]
    public string Path { get; set; }
}

/// <summary></summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigSpecOpenapiDocuments
{
    /// <summary>The OpenAPI Specification document file.</summary>
    [JsonPropertyName("document")]
    public APIGatewayAPIConfigSpecOpenapiDocumentsDocument Document { get; set; }
}

/// <summary>The project that this resource belongs to.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigSpecProjectRef
{
    /// <summary>Allowed value: The `name` field of a `Project` resource.</summary>
    [JsonPropertyName("external")]
    public string? External { get; set; }

    /// <summary>Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names</summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/</summary>
    [JsonPropertyName("namespace")]
    public string? Namespace { get; set; }
}

/// <summary></summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigSpec
{
    /// <summary>Immutable. The API to attach the config to.</summary>
    [JsonPropertyName("api")]
    public string Api { get; set; }

    /// <summary>Immutable. Creates a unique name beginning with the specified prefix. If this and api_config_id are unspecified, a random value is chosen for the name.</summary>
    [JsonPropertyName("apiConfigIdPrefix")]
    public string? ApiConfigIdPrefix { get; set; }

    /// <summary>A user-visible name for the API.</summary>
    [JsonPropertyName("displayName")]
    public string? DisplayName { get; set; }

    /// <summary>Immutable. Immutable. Gateway specific configuration. If not specified, backend authentication will be set to use OIDC authentication using the default compute service account.</summary>
    [JsonPropertyName("gatewayConfig")]
    public APIGatewayAPIConfigSpecGatewayConfig? GatewayConfig { get; set; }

    /// <summary>gRPC service definition files. If specified, openapiDocuments must not be included.</summary>
    [JsonPropertyName("grpcServices")]
    public IList<APIGatewayAPIConfigSpecGrpcServices>? GrpcServices { get; set; }

    /// <summary>Optional. Service Configuration files. At least one must be included when using gRPC service definitions. See https://cloud.google.com/endpoints/docs/grpc/grpc-service-config#service_configuration_overview for the expected file contents. If multiple files are specified, the files are merged with the following rules: * All singular scalar fields are merged using "last one wins" semantics in the order of the files uploaded. * Repeated fields are concatenated. * Singular embedded messages are merged using these rules for nested fields.</summary>
    [JsonPropertyName("managedServiceConfigs")]
    public IList<APIGatewayAPIConfigSpecManagedServiceConfigs>? ManagedServiceConfigs { get; set; }

    /// <summary>OpenAPI specification documents. If specified, grpcServices and managedServiceConfigs must not be included.</summary>
    [JsonPropertyName("openapiDocuments")]
    public IList<APIGatewayAPIConfigSpecOpenapiDocuments>? OpenapiDocuments { get; set; }

    /// <summary>The project that this resource belongs to.</summary>
    [JsonPropertyName("projectRef")]
    public APIGatewayAPIConfigSpecProjectRef ProjectRef { get; set; }

    /// <summary>Immutable. Optional. The apiConfigId of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default.</summary>
    [JsonPropertyName("resourceID")]
    public string? ResourceID { get; set; }
}

/// <summary></summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigStatusConditions
{
    /// <summary>Last time the condition transitioned from one status to another.</summary>
    [JsonPropertyName("lastTransitionTime")]
    public string? LastTransitionTime { get; set; }

    /// <summary>Human-readable message indicating details about last transition.</summary>
    [JsonPropertyName("message")]
    public string? Message { get; set; }

    /// <summary>Unique, one-word, CamelCase reason for the condition's last transition.</summary>
    [JsonPropertyName("reason")]
    public string? Reason { get; set; }

    /// <summary>Status is the status of the condition. Can be True, False, Unknown.</summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }

    /// <summary>Type is the type of the condition.</summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }
}

/// <summary></summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfigStatus
{
    /// <summary>Conditions represent the latest available observation of the resource's current state.</summary>
    [JsonPropertyName("conditions")]
    public IList<APIGatewayAPIConfigStatusConditions>? Conditions { get; set; }

    /// <summary>The resource name of the API Config.</summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>ObservedGeneration is the generation of the resource that was most recently observed by the Config Connector controller. If this is equal to metadata.generation, then that means that the current reported status reflects the most recent desired state of the resource.</summary>
    [JsonPropertyName("observedGeneration")]
    public int? ObservedGeneration { get; set; }

    /// <summary>The ID of the associated Service Config (https://cloud.google.com/service-infrastructure/docs/glossary#config).</summary>
    [JsonPropertyName("serviceConfigId")]
    public string? ServiceConfigId { get; set; }
}

/// <summary></summary>
[global::System.CodeDom.Compiler.GeneratedCode("KubernetesCRDModelGen.Tool", "1.0.0.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class APIGatewayAPIConfig
{
    /// <summary>apiVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources</summary>
    [JsonPropertyName("apiVersion")]
    public string? ApiVersion { get; set; }

    /// <summary>kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds</summary>
    [JsonPropertyName("kind")]
    public string? Kind { get; set; }

    /// <summary></summary>
    [JsonPropertyName("metadata")]
    public APIGatewayAPIConfigMetadata? Metadata { get; set; }

    /// <summary></summary>
    [JsonPropertyName("spec")]
    public APIGatewayAPIConfigSpec Spec { get; set; }

    /// <summary></summary>
    [JsonPropertyName("status")]
    public APIGatewayAPIConfigStatus? Status { get; set; }
}