apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.121.0
  creationTimestamp: 
  labels:
    cnrm.cloud.google.com/managed-by-kcc: true
    cnrm.cloud.google.com/stability-level: alpha
    cnrm.cloud.google.com/system: true
  name: dataformrepositories.dataform.cnrm.cloud.google.com
spec:
  group: dataform.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: DataformRepository
    listKind: DataformRepositoryList
    plural: dataformrepositories
    shortNames:
    - gcpdataformrepository
    - gcpdataformrepositories
    singular: dataformrepository
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: When 'True', the most recent reconcile of the resource succeeded
      jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - description: The reason for the value in 'Ready'
      jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Status
      type: string
    - description: The last transition time for the value in 'Status'
      jsonPath: .status.conditions[?(@.type=='Ready')].lastTransitionTime
      name: Status Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DataformRepository is the Schema for the dataform API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              gitRemoteSettings:
                description: Optional. If set, configures this repository to be linked to a Git remote.
                properties:
                  authenticationTokenSecretVersion:
                    description: The name of the Secret Manager secret version to use as an authentication token for Git operations. Must be in the format projects/* /secrets/* /versions/*.
                    type: string
                  defaultBranch:
                    description: The Git remote's default branch name.
                    type: string
                  tokenStatus:
                    description: Indicates the status of the Git access token. https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories#TokenStatus.
                    type: string
                  url:
                    description: The Git remote's URL.
                    type: string
                required:
                - authenticationTokenSecretVersion
                - defaultBranch
                - url
                type: object
              projectRef:
                description: The project that this resource belongs to.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                properties:
                  external:
                    description: The `projectID` field of a project, when not managed by KCC.
                    type: string
                  kind:
                    description: The kind of the Project resource; optional but must be `Project` if provided.
                    type: string
                  name:
                    description: The `name` field of a `Project` resource.
                    type: string
                  namespace:
                    description: The `namespace` field of a `Project` resource.
                    type: string
                type: object
              region:
                description: Immutable. A reference to the region.
                type: string
              resourceID:
                description: Immutable. Optional. The name of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default.
                type: string
              workspaceCompilationOverrides:
                description: Optional. If set, fields of workspaceCompilationOverrides override the default compilation settings that are specified in dataform.json when creating workspace-scoped compilation results.
                properties:
                  defaultDatabase:
                    description: Optional. The default database (Google Cloud project ID).
                    type: string
                  schemaSuffix:
                    description: Optional. The suffix that should be appended to all schema (BigQuery dataset ID) names.
                    type: string
                  tablePrefix:
                    description: Optional. The prefix that should be prepended to all table names.
                    type: string
                type: object
            required:
            - projectRef
            - region
            type: object
          status:
            properties:
              conditions:
                description: Conditions represent the latest available observations of the DataformRepository's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True, False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
              observedGeneration:
                description: ObservedGeneration is the generation of the resource that was most recently observed by the Config Connector controller. If this is equal to metadata.generation, then that means that the current reported status reflects the most recent desired state of the resource.
                format: int64
                type: integer
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: 
  storedVersions: 
