using k8s;
using k8s.Models;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

namespace KubernetesCRDModelGen.Models.vertexai.cnrm.cloud.google.com;
/// <summary>Threshold for categorical features of anomaly detection. This is shared by all types of Featurestore Monitoring for categorical features (i.e. Features with type (Feature.ValueType) BOOL or STRING).</summary>
public partial class V1alpha1VertexAIFeaturestoreEntityTypeSpecMonitoringConfigCategoricalThresholdConfig
{
    /// <summary>Specify a threshold value that can trigger the alert. For categorical feature, the distribution distance is calculated by L-inifinity norm. Each feature must have a non-zero threshold if they need to be monitored. Otherwise no alert will be triggered for that feature. The default value is 0.3.</summary>
    [JsonPropertyName("value")]
    public double Value { get; set; }
}

/// <summary>The config for ImportFeatures Analysis Based Feature Monitoring.</summary>
public partial class V1alpha1VertexAIFeaturestoreEntityTypeSpecMonitoringConfigImportFeaturesAnalysis
{
    /// <summary>Defines the baseline to do anomaly detection for feature values imported by each [entityTypes.importFeatureValues][] operation. The value must be one of the values below: * LATEST_STATS: Choose the later one statistics generated by either most recent snapshot analysis or previous import features analysis. If non of them exists, skip anomaly detection and only generate a statistics. * MOST_RECENT_SNAPSHOT_STATS: Use the statistics generated by the most recent snapshot analysis if exists. * PREVIOUS_IMPORT_FEATURES_STATS: Use the statistics generated by the previous import features analysis if exists.</summary>
    [JsonPropertyName("anomalyDetectionBaseline")]
    public string? AnomalyDetectionBaseline { get; set; }

    /// <summary>Whether to enable / disable / inherite default hebavior for import features analysis. The value must be one of the values below: * DEFAULT: The default behavior of whether to enable the monitoring. EntityType-level config: disabled. * ENABLED: Explicitly enables import features analysis. EntityType-level config: by default enables import features analysis for all Features under it. * DISABLED: Explicitly disables import features analysis. EntityType-level config: by default disables import features analysis for all Features under it.</summary>
    [JsonPropertyName("state")]
    public string? State { get; set; }
}

/// <summary>Threshold for numerical features of anomaly detection. This is shared by all objectives of Featurestore Monitoring for numerical features (i.e. Features with type (Feature.ValueType) DOUBLE or INT64).</summary>
public partial class V1alpha1VertexAIFeaturestoreEntityTypeSpecMonitoringConfigNumericalThresholdConfig
{
    /// <summary>Specify a threshold value that can trigger the alert. For numerical feature, the distribution distance is calculated by Jensen–Shannon divergence. Each feature must have a non-zero threshold if they need to be monitored. Otherwise no alert will be triggered for that feature. The default value is 0.3.</summary>
    [JsonPropertyName("value")]
    public double Value { get; set; }
}

/// <summary>The config for Snapshot Analysis Based Feature Monitoring.</summary>
public partial class V1alpha1VertexAIFeaturestoreEntityTypeSpecMonitoringConfigSnapshotAnalysis
{
    /// <summary>The monitoring schedule for snapshot analysis. For EntityType-level config: unset / disabled = true indicates disabled by default for Features under it; otherwise by default enable snapshot analysis monitoring with monitoringInterval for Features under it.</summary>
    [JsonPropertyName("disabled")]
    public bool? Disabled { get; set; }

    /// <summary>DEPRECATED. `monitoring_interval` is deprecated and will be removed in a future release. Configuration of the snapshot analysis based monitoring pipeline running interval. The value is rolled up to full day.  A duration in seconds with up to nine fractional digits, terminated by 's'. Example: "3.5s".</summary>
    [JsonPropertyName("monitoringInterval")]
    public string? MonitoringInterval { get; set; }

    /// <summary>Configuration of the snapshot analysis based monitoring pipeline running interval. The value indicates number of days. The default value is 1. If both FeaturestoreMonitoringConfig.SnapshotAnalysis.monitoring_interval_days and [FeaturestoreMonitoringConfig.SnapshotAnalysis.monitoring_interval][] are set when creating/updating EntityTypes/Features, FeaturestoreMonitoringConfig.SnapshotAnalysis.monitoring_interval_days will be used.</summary>
    [JsonPropertyName("monitoringIntervalDays")]
    public int? MonitoringIntervalDays { get; set; }

    /// <summary>Customized export features time window for snapshot analysis. Unit is one day. The default value is 21 days. Minimum value is 1 day. Maximum value is 4000 days.</summary>
    [JsonPropertyName("stalenessDays")]
    public int? StalenessDays { get; set; }
}

/// <summary>The default monitoring configuration for all Features under this EntityType.  If this is populated with [FeaturestoreMonitoringConfig.monitoring_interval] specified, snapshot analysis monitoring is enabled. Otherwise, snapshot analysis monitoring is disabled.</summary>
public partial class V1alpha1VertexAIFeaturestoreEntityTypeSpecMonitoringConfig
{
    /// <summary>Threshold for categorical features of anomaly detection. This is shared by all types of Featurestore Monitoring for categorical features (i.e. Features with type (Feature.ValueType) BOOL or STRING).</summary>
    [JsonPropertyName("categoricalThresholdConfig")]
    public V1alpha1VertexAIFeaturestoreEntityTypeSpecMonitoringConfigCategoricalThresholdConfig? CategoricalThresholdConfig { get; set; }

    /// <summary>The config for ImportFeatures Analysis Based Feature Monitoring.</summary>
    [JsonPropertyName("importFeaturesAnalysis")]
    public V1alpha1VertexAIFeaturestoreEntityTypeSpecMonitoringConfigImportFeaturesAnalysis? ImportFeaturesAnalysis { get; set; }

    /// <summary>Threshold for numerical features of anomaly detection. This is shared by all objectives of Featurestore Monitoring for numerical features (i.e. Features with type (Feature.ValueType) DOUBLE or INT64).</summary>
    [JsonPropertyName("numericalThresholdConfig")]
    public V1alpha1VertexAIFeaturestoreEntityTypeSpecMonitoringConfigNumericalThresholdConfig? NumericalThresholdConfig { get; set; }

    /// <summary>The config for Snapshot Analysis Based Feature Monitoring.</summary>
    [JsonPropertyName("snapshotAnalysis")]
    public V1alpha1VertexAIFeaturestoreEntityTypeSpecMonitoringConfigSnapshotAnalysis? SnapshotAnalysis { get; set; }
}

/// <summary></summary>
public partial class V1alpha1VertexAIFeaturestoreEntityTypeSpec
{
    /// <summary>Optional. Description of the EntityType.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }

    /// <summary>Immutable. The name of the Featurestore to use, in the format projects/{project}/locations/{location}/featurestores/{featurestore}.</summary>
    [JsonPropertyName("featurestore")]
    public string Featurestore { get; set; }

    /// <summary>The default monitoring configuration for all Features under this EntityType.  If this is populated with [FeaturestoreMonitoringConfig.monitoring_interval] specified, snapshot analysis monitoring is enabled. Otherwise, snapshot analysis monitoring is disabled.</summary>
    [JsonPropertyName("monitoringConfig")]
    public V1alpha1VertexAIFeaturestoreEntityTypeSpecMonitoringConfig? MonitoringConfig { get; set; }

    /// <summary>Config for data retention policy in offline storage. TTL in days for feature values that will be stored in offline storage. The Feature Store offline storage periodically removes obsolete feature values older than offlineStorageTtlDays since the feature generation time. If unset (or explicitly set to 0), default to 4000 days TTL.</summary>
    [JsonPropertyName("offlineStorageTtlDays")]
    public int? OfflineStorageTtlDays { get; set; }

    /// <summary>Immutable. Optional. The name of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default.</summary>
    [JsonPropertyName("resourceID")]
    public string? ResourceID { get; set; }
}

/// <summary></summary>
public partial class V1alpha1VertexAIFeaturestoreEntityTypeStatusConditions
{
    /// <summary>Last time the condition transitioned from one status to another.</summary>
    [JsonPropertyName("lastTransitionTime")]
    public string? LastTransitionTime { get; set; }

    /// <summary>Human-readable message indicating details about last transition.</summary>
    [JsonPropertyName("message")]
    public string? Message { get; set; }

    /// <summary>Unique, one-word, CamelCase reason for the condition's last transition.</summary>
    [JsonPropertyName("reason")]
    public string? Reason { get; set; }

    /// <summary>Status is the status of the condition. Can be True, False, Unknown.</summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }

    /// <summary>Type is the type of the condition.</summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }
}

/// <summary></summary>
public partial class V1alpha1VertexAIFeaturestoreEntityTypeStatus
{
    /// <summary>Conditions represent the latest available observation of the resource's current state.</summary>
    [JsonPropertyName("conditions")]
    public IList<V1alpha1VertexAIFeaturestoreEntityTypeStatusConditions>? Conditions { get; set; }

    /// <summary>The timestamp of when the featurestore was created in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.</summary>
    [JsonPropertyName("createTime")]
    public string? CreateTime { get; set; }

    /// <summary>Used to perform consistent read-modify-write updates.</summary>
    [JsonPropertyName("etag")]
    public string? Etag { get; set; }

    /// <summary>ObservedGeneration is the generation of the resource that was most recently observed by the Config Connector controller. If this is equal to metadata.generation, then that means that the current reported status reflects the most recent desired state of the resource.</summary>
    [JsonPropertyName("observedGeneration")]
    public int? ObservedGeneration { get; set; }

    /// <summary>The region of the EntityType.</summary>
    [JsonPropertyName("region")]
    public string? Region { get; set; }

    /// <summary>The timestamp of when the featurestore was last updated in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.</summary>
    [JsonPropertyName("updateTime")]
    public string? UpdateTime { get; set; }
}

[KubernetesEntity(Group = KubeGroup, Kind = KubeKind, ApiVersion = KubeApiVersion, PluralName = KubePluralName)]
/// <summary></summary>
public partial class V1alpha1VertexAIFeaturestoreEntityType : IKubernetesObject<V1ObjectMeta>, ISpec<V1alpha1VertexAIFeaturestoreEntityTypeSpec>, IStatus<V1alpha1VertexAIFeaturestoreEntityTypeStatus>
{
    public const string KubeApiVersion = "v1alpha1";
    public const string KubeKind = "VertexAIFeaturestoreEntityType";
    public const string KubeGroup = "vertexai.cnrm.cloud.google.com";
    public const string KubePluralName = "vertexaifeaturestoreentitytypes";
    /// <summary></summary>
    [JsonPropertyName("apiVersion")]
    public string ApiVersion { get; set; }

    /// <summary></summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; }

    /// <summary></summary>
    [JsonPropertyName("metadata")]
    public V1ObjectMeta Metadata { get; set; }

    /// <summary></summary>
    [JsonPropertyName("spec")]
    public V1alpha1VertexAIFeaturestoreEntityTypeSpec Spec { get; set; }

    /// <summary></summary>
    [JsonPropertyName("status")]
    public V1alpha1VertexAIFeaturestoreEntityTypeStatus? Status { get; set; }
}