name: PR Build & Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-test:
    name: Build & Test
    permissions:
      contents: read
    uses: IvanJosipovic/templates/.github/workflows/csharp-build-test.yaml@main
