name: sync-crds

on:
  push:
    branches:
      - alpha
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  sync-crds:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Clean Models
        run: rm -rf ./src/Models/KubernetesCRDModelGen*

      - name: Sync CRDs
        run: dotnet run --project ./src/KubernetesCRDModelGen.Sync/KubernetesCRDModelGen.Sync.csproj --ModelDir ../Models

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: sync-charts
            commit-message: "feat: Update CRDs"
            title: "feat: Update CRDs"
            body: "Automated CRD Sync"